### ISSUE TITLE
banner disapears and re appears constantly while moving mouse across the message

### ISSUE THREAD

**Issue by jack652** [domi-btnr/BetterDiscordStuff#21]
### Discord Account

YeetDabMcFapDab#0971

### Describe the bug

the banner from the invite disapears and re appears constantly while moving mouse across the message

https://user-images.githubusercontent.com/48365199/202779787-94189bab-2a20-4d1f-b848-e530dcdddb6c.mp4

### How can I recreate this bug

1. mouse over a message that has an invite to a server that has a banner
2. move mouse around

**Comment by HypedDomi** [comment]
I don't have much time and motivation for BD plugins at the moment. I try to fix this after my exam period

**Comment by PitchBlackNights** [comment]
The error happens in this code block (lines 266-274):
```javascript
} else if (this.settings.bannerType === 0) {
	component.props.children.splice(2, 0, React.createElement("img", {
     	className: `${config.info.name}-banner`,
        src: `https://cdn.discordapp.com/banners/${guild.id}/${guild.banner}.gif?size=1024`,
        style: { width: "100%", height: "auto", maxHeight: "100px", borderRadius: "5px", objectFit: "cover" },
        onError: (e) => { e.target.onError = null, e.target.src = `https://cdn.discordapp.com/banners/${guild.id}/${guild.banner}.png?size=1024` }
	}));
    if (guild.features.includes("INVITE_SPLASH")) component.props.children.splice(0, 1);
}
```

It happens when the server doesn't have an animated banner. The plugin first requests the animated banner (even if there isn't an animated banner), and if that errors, it grabs the static image. This, as you can expect, causes a delay which makes the image flicker.

The reason it is flickering is that the plugin runs every time the message is in focus, and the mouse is moving.

The only way I think this can be prevented is to reengineer the banner requests to request a static image first, then it can request the animated banner.

**Comment by HypedDomi** [comment]
I can check the Guild Features if it has an animated banner. Im trying to fix this quick

**Comment by PitchBlackNights** [comment]
Oh, well that would work too
